package com.noop.nutrition

import org.json.JSONArray
import org.junit.Assert.*
import org.junit.Test
import java.io.File

class NutritionMealTest {
    @Test fun estimatesMatchStandaloneSwiftOracle() {
        val fixtures = File("../../Tools/nutrition-oracle")
        val cases = JSONArray(File(fixtures, "estimates.json").readText())
        val actual = (0 until cases.length()).joinToString("\n", postfix = "\n") { index ->
            val item = cases.getJSONObject(index)
            val name = item.getString("case")
            try {
                val meal = NutritionMeal.parseEstimate(item.getString("input"))
                "$name:${meal.name}|${meal.portion}|${meal.calories}|${meal.protein}|${meal.carbs}|${meal.fat}"
            } catch (_: Exception) { "$name:rejected" }
        }
        // Generated by compiling and running the actual Swift model, not copied from Kotlin.
        assertEquals(File(fixtures, "swift-oracle.txt").readText(), actual)
    }

    @Test fun storedMealRoundTripsAllFields() {
        val meal = NutritionMeal(name = "Lunch", timestamp = 1790990400000.0, portion = "1 bowl",
            calories = 540.5, protein = 35.0, carbs = 65.0, fat = 15.0,
            notes = "Estimate", photo = "photo.jpg", provider = "openAI", model = "gpt-5-mini")
        assertEquals(meal, NutritionMeal.fromJson(meal.toJson()))
    }

    @Test fun invalidNumbersAndIdsCannotBeSaved() {
        assertFalse(NutritionMeal(name = "Lunch", calories = Double.NaN).isValid)
        assertFalse(NutritionMeal(name = "Lunch", protein = Double.POSITIVE_INFINITY).isValid)
        assertFalse(NutritionMeal(name = "Lunch", timestamp = -1.0).isValid)
        assertFalse(NutritionMeal(name = "Lunch", id = "../photo").isValid)
    }
}
